### ISSUE TITLE
MFCC extractor returns NaNs

### ISSUE THREAD

**Issue by stefanpantic** [ar1st0crat/NWaves#16]
I keep getting NaNs when I try to compute MFCC on my .wav audio file. I can email the audio file if needed as GitHub doesn't support uploading .wav files.

Code:
```
private static readonly MfccExtractor MfccExtractor = new MfccExtractor(
            16000,
            64,
            0.025,
            0.01,
            64,
            fftSize: 512,
            preEmphasis: 0.97,
            includeEnergy: true,
            dctType: "4",
            nonLinearity: NonLinearityType.LogE);
var samples = new WaveFile(new FileStream("./file.wav", FileMode.Open))[Channels.Left].Samples;
var mfccSamples  = MfccExtractor.ComputeFrom(samples);
```

**Comment by ar1st0crat** [comment]
If you're referring to the previously discussed nuance with ```-INF``` for log-energy, I haven't fixed it so far (because I don't think it's a bug at all). If you're talking about something else - then email me your file.

**Comment by stefanpantic** [comment]
This is a separate issue. I'll email you the problematic file.

**Comment by ar1st0crat** [comment]
Are you sure you're processing exactly this file? I ran the extractor with your config and there are no NaNs here. At what time positions NaNs occur?

**Comment by ataboo** [comment]
Just in-case anyone googles this too:

I was consistently getting a row of NANs at random frames samples when I was asynchronously running MFCC values on multiple samples.  Turns out I was building the extractor in the constructor and reusing the same instance across threads causing a race condition.  

I've since fixed it by building a new extractor per task and it works fine.

**Comment by ar1st0crat** [comment]
Yes, feature extractors are not thread-safe by design. I'll add this important note to the corresponding page in wiki documenation.
