### ISSUE TITLE
Error when running Operation.TimeStretch

### ISSUE THREAD

**Issue by gheyret** [ar1st0crat/NWaves#4]
Hi @ar1st0crat  thank you  for wonderful library.
when I run the program , I got a error. 

[qb010005.zip](https://github.com/ar1st0crat/NWaves/files/2786223/qb010005.zip)

using (var stream = new FileStream("qb010005.wav", FileMode.Open))
{
	orgwav = new WaveFile(stream)[0];
	newwav = Operation.TimeStretch(orgwav,1.2);
	using (var wst = new FileStream("mynew.wav", FileMode.Create))
	{
		newwavFile = new WaveFile(newwav);
		newwavFile.SaveTo(wst);
	}
}

But when I change 1.2 to 0.8 it's ok.

**Comment by ar1st0crat** [comment]
Hi @gheyret ! Thank you for your kind words and for finding a bug!
Obviously, couple of checks for marginal cases are missing in my current implementation of the Wsola algorithm. When parameter is set to "1.201", there are no exceptions (so if you need a solution ASAP, you can use 1.201 instead of 1.2, or just slightly tweak parameter "overlapSize" or "deltaSize" in Wsola.cs file).

In any case, I'm not really satisfied with the way the TSM algorithms (_Wsola and phase vocoder_) are currently implemented here, and I hope very soon I'll rewrite/test them and make the corresponding commit. When it happens, I'll comment here once again and close this issue.

**Comment by ar1st0crat** [comment]
Ok, I've made a couple of commits with improvements in TSM code, and now, I think, this issue can be closed. Currently, the three algorithms can be applied for time-stretching: 1) Classical phase vocoder (PV), 2) Phase vocoder with Identity phase locking (PVIPL) and 3) WSOLA.
WSOLA is good for speech signals, while in general PVIPL sounds better.

```C#
// WSOLA with default parameters
newwav = Operation.TimeStretch(orgwav, 1.2);

// WSOLA with user-defined parameters
newwav = Operation.TimeStretch(orgwav, 1.2, windowSize: 700, hopSize: 120);

// PVIPL with default parameters
newwav = Operation.TimeStretch(orgwav, 1.2, algorithm: TsmAlgorithm.PhaseVocoderPhaseLocking);

// PVIPL with user-defined parameters
newwav = Operation.TimeStretch(orgwav, 1.2, hopSize: 128, windowSize: 512, algorithm: TsmAlgorithm.PhaseVocoderPhaseLocking);
```

Also, your file contains some amplitudes that are very close to the maximum value. PV-based techniques may lead to insignificant amplitude changes and, in this case, some clipping in corresponding regions. So I would suggest slightly attenuate the "loud" signal before applying PV or PVIPL. Something like this:

```C#
var maxAmp = orgwav.Samples.Max(s => Math.Abs(s));
if (maxAmp > 0.95f)
{
    var wav = orgwav.Copy();
    wav.Amplify(0.75f);

    newwav = Operation.TimeStretch(orgwav, 1.2, algorithm: TsmAlgorithm.PhaseVocoderPhaseLocking);
}
```
