### ISSUE TITLE
exception on Convolver.convolve function

### ISSUE THREAD

**Issue by Azam-Mokhtari** [ar1st0crat/NWaves#49]
Hello
I need to call convolution function using Convolver, but always fall in exception.
I have input and kernel arrays with different sizes. I tried to use fft_size  with various values, but none of them worked

input array length: 7992
kernel array length: 30
fft_size values: 1024, 16, ...
exception Message:
"Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."

exception callstack:
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at NWaves.Utils.MemoryOperationExtensions.FastCopyTo(Single[] source, Single[] destination, Int32 size, Int32 sourceOffset, Int32 destinationOffset)
   at NWaves.Operations.Convolution.Convolver.Convolve(Single[] input, Single[] kernel, Single[] output)

Could you please check this issue and tell me what is proper fft_size?
Thanks

**Comment by ar1st0crat** [comment]
Hello,

the following code doesn't throw exceptions:

```C#

var c = new Convolver();
		
var input = new DiscreteSignal(1, 7992);
var kernel = new DiscreteSignal(1, 30);
		
var res = c.Convolve(input, kernel);

```

i.e., if you're not sure about the FFT size, then simply don't specify it (the library will autodeduce it from signal sizes as ```fft_size=len(input)+len(kernel)-1```, according to DSP theory). Otherwise, it's expected that the programmer understands completely what's goin' on, and you have to guarantee that FFT size is not less than ```fft_size```.

---

PS. If the reason why you set FFT size to 1024 is because you intended to convolve first 1024 samples with kernel (not the entire input signal of 7992 samples), then write this:

```C#
var res = c.Convolve(input.First(1024), kernel);
```

**Comment by Azam-Mokhtari** [comment]
Thanks a lot for your answer, This can solve the problem.
Or I can use convolve function with DiscreteSignal input and DiscreteSignal kernel that have various size.
Thank you so much.

**Comment by ar1st0crat** [comment]
Ok, I re-read your initial comment, and you're working with float arrays (providing code would be better, though).

Anyway - surely, you can still work with float arrays (there's no need to switch to ```DiscreteSignal```) - just make sure that the length of output array is sufficient and proper minimum fft size is set in the constructor (according to my previous comment).
